version: '3'

services:
    bot:
        build: .
        env_file: .env
        restart: on-failure
        command: ["python", "main.py"]
        depends_on:
          - mysql

    calculator:
        build: .
        env_file: .env
        restart: unless-stopped
        command: ["python", "calculator.py"]
        depends_on:
          - mysql

    submitter:
        build: .
        env_file: .env
        restart: on-failure
        command: ["python", "submitter.py"]
        depends_on:
          - mysql

    leaderboard:
        build: .
        env_file: .env
        restart: unless-stopped
        command: ["python", "leaderboard.py"]
        depends_on:
          - mysql

    payroll:
        build: .
        env_file: .env
        restart: unless-stopped
        command: ["python", "payroll.py"]
        depends_on:
          - mysql

    api:
        image: golang
        env_file: .env
        restart: unless-stopped
        command: ["go", "run", "main.go"]
        depends_on:
          - mysql

    http:
        build:
            context: .
            dockerfile: docker/Dockerfile-caddy
        env_file: .env
        restart: unless-stopped
        ports:
          - 2015:2015
        depends_on:
          - api

    mysql:
        image: mariadb:10.2.15
        env_file: .env
        restart: unless-stopped
