version: '3'

services:
    bot:
        build: .
        env_file: .env
        depends_on:
          - mysql
        environment:
          - MYSQL_DATABASE=mysql
          - MYSQL_USER=mysql
          - MYSQL_PASSWORD=strongpass!word

    mysql:
        image: mariadb
        env_file: .env
        environment:
          - MYSQL_DATABASE=mysql
          - MYSQL_USER=mysql
          - MYSQL_PASSWORD=strongpass!word
          - MYSQL_RANDOM_ROOT_PASSWORD=yes
