version: '3'

services:
    bot:
        build: .
        env_file: .env
        depends_on:
          - mysql
        environment:
          - MYSQL_DATABASE=mysql
          - MYSQL_USER=mysql
          - MYSQL_PASSWORD=strongpass!word

    calculator:
        build: .
        env_file: .env
        command: ["python", "calculator.py"]
        depends_on:
          - mysql
        environment:
          - MYSQL_DATABASE=mysql
          - MYSQL_USER=mysql
          - MYSQL_PASSWORD=strongpass!word

    submitter:
        build: .
        env_file: .env
        command: ["python", "submitter.py"]
        depends_on:
          - mysql
        environment:
          - MYSQL_DATABASE=mysql
          - MYSQL_USER=mysql
          - MYSQL_PASSWORD=strongpass!word

    api:
        build: .
        env_file: .env
        command: ["python", "api.py"]
        ports:
         - 5000:5000
        depends_on:
          - mysql
        environment:
          - MYSQL_DATABASE=mysql
          - MYSQL_USER=mysql
          - MYSQL_PASSWORD=strongpass!word

    mysql:
        image: mariadb
        env_file: .env
        environment:
          - MYSQL_DATABASE=mysql
          - MYSQL_USER=mysql
          - MYSQL_PASSWORD=strongpass!word
          - MYSQL_RANDOM_ROOT_PASSWORD=yes
